### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by ColonelKai** [ColonelKai/LockednLoaded#1]
## BUG FIXES
**1.6.17**
- [ ] Internal Code Refactors. 
- [ ] Add better missile cleanup for future radar implementation.

## 1.7 | Quality of Life Updates

**1.7.1**
- [ ] Change missile naming scheme, add new Surface-to-Air Missiles (SAM).
- [ ] Change ground-to-ground missile trajectory to give missile impacts some more oompf.
- [ ] Add missile sound effects for MORE OOMPF.

**1.7.2**
- [ ] Add IFF (Identification of Friend or Foe) IDs. These will replace the current playerIDs. They will work by assigning every launcher, radar and player an IFF. They will have books similar as to before, which will have an IFF-ID. You will be able to use the book to assign.
- [ ] Make sure SAMs cannot shoot down missiles wit hthe same IFF-ID as their launcher. Same goes with players and elytra launchers.

## 1.8 | Radar & SAM Updates

**1.8.1**
- [ ] Add Radar multiblocks. They should have signs that display the direction and distance of missiles. IFF-Compatible. Optimisation is key. The radars range should be adjustable. 

**1.8.2**
- [ ] Add Player-Radars. They will detect a player either with an elytra or in the line of sight. IFF-compatible.

**1.8.3**
- [ ] Make SAMs require a radar. They radar will ping nearby (distance depending on the radar model) SAM launchers with the same IFF-ID, and if they have a missile that has the range, it will shoot them down.

**1.8.4**
- [ ] Add Anti-Radiation Missiles. Basically, after being thrown into the air, it will travel to its destination like a normal rocket. However, if it finds a radar on its way there, it will lock onto it instead, and attempt to destroy it.
- [ ] [OPTIONAL] Add jammers. I might try to make them require Slimefun energy, and then have them jam a radius depending on their tier.
